### ISSUE TITLE
copy response to clipboard

### ISSUE THREAD

**Issue by Dizardmk** [xuanzhi33/vscode-calculator#1]
Hello! Thank you so much for this extension, it is very useful for me!
I would like you to add the ability to copy the result of the calculation to the clipboard so that you can use it (via ctrl-v). It would be great if you added this, thanks again!

**Comment by xuanzhi33** [comment]
Thank you very much for your use and suggestions, I will add the function of copy to clipboard in the next version.

**Comment by Dizardmk** [comment]
this is very awesome, big thx to you

**Comment by xuanzhi33** [comment]
I have just added the copy function and released the new version. You can update the extension to try this out.
